accounts/urls.py
from django.urls import path, include, reverse, reverse_lazy
from django.contrib.auth import views as auth_views

from .views import SignUpView

app_name = 'accounts'
urlpatterns = [
    # path("", include("django.contrib.auth.urls"), name="accounts"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("password_reset/", auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path("password_reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    # The view for the main page where all books will be displayed
    path('', views.LibraryBook.as_view(), name='index'),

    # The view for creating a book
    path('create/', views.CreateBookView.as_view(), name='create'),

    # The view that will edit an already existing book
    path('edit/<int:num>', views.EditBookView.as_view(), name='edit'),

    # The view that will confirm the deletion of a book
    path('delete/<pk>/', views.DeleteConfirmView.as_view(), name='delete'),

    # The view to display books ready to be bought
    path('shop/', views.ShopView.as_view(), name='shop'),

    # Book purchase confirmation will be displayed in this view.
    path('shop/<int:num>', views.BuyBookView.as_view(), name='buyBook'),

    # User-created books will be displayed in this view.
    path('owned/', views.OwnedBooksView.as_view(), name='ownedBooks'),

    # User-purchased books will be displayed in this view.
    path('purchased/', views.PurchasedBooksView.as_view(), name='purchasedBooks'),
]

books/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('uwu-admin-panel/', admin.site.urls),
    path('', include('book.urls'), name="books"),
    path("accounts/", include("accounts.urls")),
]

book/models.py
from django.db import models
from django.contrib.auth.models import User


# This is the model that will structure how book information will be saved in the database.
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    publication_date = models.DateTimeField('date published')
    num_pages = models.IntegerField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='related_primary_manual_roats')
    description = models.CharField(max_length=1000)
    gender = models.CharField(max_length=50)
    price = models.FloatField()

    # ManyToManyField behave like a list. It will store a queryset of foreign key of User to know which user purchased
    # the book.
    purchasers = models.ManyToManyField(User, related_name='related_secondary_manual_roats')


# This model will store the wallet information of each user to give them the capability to buy books from the store
class Wallet(models.Model):
    balance = models.FloatField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

book/forms.py
from django import forms
from .models import Book
from django.utils import timezone


# This is an empty form used for confirmation views
class ConfirmationForm(forms.Form):
    pass


# This form will store the fields that will be modified in the book
class EditBookForm(forms.Form):
    title = forms.CharField()
    author = forms.CharField()
    description = forms.CharField()
    gender = forms.CharField()
    num_pages = forms.IntegerField()
    price = forms.FloatField()

    def is_valid(self):
        try:
            if float(self.data.get('price')) <= 0 or float(self.data.get('num_pages')) < 0:
                return False
        except(KeyError, ValueError):
            return False
        return super().is_valid()

    # This custom def will apply the book update in the database
    def update_book(self, book):
        book.title = self.data['title']
        book.author = self.data['author']
        book.description = self.data['description']
        book.gender = self.data['gender']
        book.num_pages = self.data['num_pages']
        book.price = self.data['price']
        book.save()


# This class-based form will store the fields in order to create a new book
class CreateBookForm(forms.Form):
    title = forms.CharField()
    author = forms.CharField()
    description = forms.CharField()
    gender = forms.CharField()
    num_pages = forms.IntegerField()
    price = forms.FloatField()

    def is_valid(self):
        try:
            if float(self.data.get('price')) < 0 or float(self.data.get('num_pages')) < 0:
                return False
        except(KeyError, ValueError):
            return False
        return super().is_valid()

    # This custom def will apply the book create in the database
    def create_book(self, user):
        now = timezone.now()
        book = Book(title=self.data['title'], author=self.data['author'], description=self.data['description'],
                    gender=self.data['gender'], num_pages=self.data['num_pages'], publication_date=now, owner=user,
                    price=self.data['price'])
        book.save()
        return book

book/views.py
from django.views import generic
from .models import Book, Wallet
from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404, redirect
from django.urls import reverse_lazy

from .forms import EditBookForm, CreateBookForm, ConfirmationForm


# The main page view. All books that are stored in the database will be returned as a queryset usable in the HTML code.
class LibraryBook(generic.TemplateView):
    template_name = "book/index.html"


# This view will display the books that the connected user have created and sold on the shop.
class OwnedBooksView(generic.ListView):
    # The choice to use the same template as purchased books view was made on purpose because they both have almost
    # the same layout
    template_name = 'book/books.html'
    model = Book
    context_object_name = 'library'

    # This def will give extra context variables in addition to existing context variables to the template
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'BOOK MANAGER'
        context['owned'] = True
        try:
            context['wallet'] = Wallet.objects.get(owner_id=self.request.user.id)
        except(KeyError, Wallet.DoesNotExist):
            return context
        return context

    def get_queryset(self):
        return Book.objects.filter(owner_id=self.request.user.id)

    # This function is called before the rendered page will be sent to the client in order to check if he is logged-in
    # or not.
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('book:index'))
        return super().dispatch(request, *args, **kwargs)


# This view will display the books purchased by the connected user in the shop.
class PurchasedBooksView(generic.ListView):
    # The choice to use the same template as owned books view was made on purpose because they both have almost
    # the same layout
    template_name = 'book/books.html'
    model = Book
    context_object_name = 'library'

    # This def will give extra context variables in addition to existing context variables to the template
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'PURCHASED BOOKS'
        context['owned'] = False
        try:
            context['wallet'] = Wallet.objects.get(owner_id=self.request.user.id)
        except(KeyError, Wallet.DoesNotExist):
            return context
        return context

    def get_queryset(self):
        return Book.objects.filter(purchasers__id=self.request.user.id)

    # This function is called before the rendered page will be sent to the client in order to check if he is logged-in
    # or not.
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('book:index'))
        return super().dispatch(request, *args, **kwargs)


# This view have a form to edit book information in the database
class EditBookView(generic.FormView):
    template_name = 'book/edit.html'
    form_class = EditBookForm
    success_url = reverse_lazy('book:ownedBooks')

    # A custom created def in order to retrieve a specific book related to the id given in the url
    def get_book(self):
        try:
            num = self.kwargs['num']
            book = Book.objects.get(pk=num)
            return book
        except(KeyError, Book.DoesNotExist):
            return None

    # This def will give extra context variables in addition to existing context variables to the template
    def get_context_data(self, **kwargs):
        try:
            book = self.get_book()
        except(KeyError, Book.DoesNotExist):
            return HttpResponseRedirect(reverse('book:index'))
        context = super().get_context_data(**kwargs)
        context['book'] = book
        return context

    # This def will be called when the client will submit the form. it will update the book fields only if the 'edit'
    # submit input have been pressed. If the 'cancel' submit input have been pressed, the update book process will be skipped.
    def form_valid(self, form):
        book = self.get_book()
        if 'edit' in self.request.POST:
            form.update_book(book)
        return super().form_valid(form)

    # This function is called before the rendered page will be sent to the client in order to check if he is logged-in
    # or not. It will also check if the book exists and if the connected user is the creator of the book
    def dispatch(self, request, *args, **kwargs):
        book = self.get_book()
        if book is None or (not self.request.user.is_authenticated or book.owner.id != self.request.user.id):
            return HttpResponseRedirect(reverse('book:index'))
        return super().dispatch(request, *args, **kwargs)


# This generic form view will create a book and add it to the database
class CreateBookView(generic.FormView):
    template_name = 'book/create.html'
    form_class = CreateBookForm  # The form that the view will be based. It is located in forms.py
    success_url = reverse_lazy('book:ownedBooks')

    def form_invalid(self, form):
        if 'cancel' in self.request.POST:
            return HttpResponseRedirect(reverse('book:index'))
        return super().form_invalid(form)

    # This function will be called when the user will submit the form
    def form_valid(self, form):
        if 'create' in self.request.POST:
            book = form.create_book(self.request.user)
        if 'cancel' in self.request.POST:
            return HttpResponseRedirect(reverse('book:index'))
        return super().form_valid(form)

    # This function is called before the page will be sent in order to verify if the user is authenticated
    # Otherwise, it will redirect it to the main page.
    def dispatch(self, request, *args, **kwargs):
        print('test: ', self.request.GET)
        print('test: ', self.request.get_full_path_info())
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('book:index'))
        return super().dispatch(request, *args, **kwargs)


# This view have the purpose to confirm if the user wants to delete the book or not.
class DeleteConfirmView(generic.DeleteView):
    template_name = 'book/delete.html'
    model = Book
    success_url = reverse_lazy('book:ownedBooks')

    # This def will be called when the user will submit the form. If the client clicked on 'cancel' submit input,
    # he will be directly redirected to the ownedBooks view in order to avoid the book suppression performed in
    # the parent form_valid def.
    def form_valid(self, form):
        if 'cancel' in self.request.POST:
            return HttpResponseRedirect(reverse('book:ownedBooks'))
        return super().form_valid(form)

    # This function is called before the page will be sent in order to verify if the user is authenticated and if
    # the creator of the book matches with the connected user.
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('book:index'))
        if self.get_object().owner.id is not request.user.id:
            return HttpResponseRedirect(reverse('book:ownedBooks'))
        return super().dispatch(request, *args, **kwargs)


# This view will display the book on sale in the shop. The connected user can buy any book he wants only if he has
# enough money in his wallet.
class ShopView(generic.ListView):
    template_name = 'book/shop.html'
    model = Book
    context_object_name = 'books'

    # This def will give extra context variables in addition to existing context variables to the template
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['wallet'] = Wallet.objects.get(owner_id=self.request.user.id)
        except(KeyError, Wallet.DoesNotExist):
            return context
        return context

    # This get_queryset override def do a special data manipulation. It will create a dictionary in order to know
    # for each book if he had already been purchased. Owned book will not be added to the dictionary.
    def get_queryset(self):
        books = Book.objects.all()
        toReturn = {}
        for book in books:
            purchased = False
            for purchaser in book.purchasers.all():
                if purchaser.id is self.request.user.id:
                    purchased = True
            if not book.owner.id == self.request.user.id:
                toReturn[book] = purchased
        return toReturn


# This view is a transaction confirmation in order to make sure that the user wants to buy a book or no.
class BuyBookView(generic.FormView):
    template_name = 'book/buy.html'
    form_class = ConfirmationForm
    success_url = reverse_lazy('book:shop')

    # This def will be called after the user have submitted the form.
    # If the client pressed the 'yes' submit input, verifications will be made in order to see if the connected user
    # have enough money and if the connected user is not the one who sold the book.
    # If all conditions have been satisfied, money will be retrieved from the user that purchased the book to the one
    # who sold the book.
    def form_valid(self, form):
        if 'yes' in self.request.POST:
            book = Book.objects.get(pk=self.kwargs['num'])
            if not book.purchasers.all().contains(self.request.user):
                wallet = Wallet.objects.get(owner_id=self.request.user.id)
                if wallet.balance >= book.price:
                    wallet.balance -= book.price
                    wallet.save()
                    owner_wallet = Wallet.objects.get(owner_id=book.owner.id)

book/templates/book/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if owned %}
        <title>Owned books</title>
    {% else %}
        <title>Purchased books</title>
    {% endif %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'book/shop.css' %}">
    <link rel="stylesheet" href="{% static 'book/books.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&display=swap" rel="stylesheet">
</head>
<body>
    <h1>{{ title }}</h1>
    <section class="wallet">
        {% if wallet %}
            <h2>YOUR WALLET: {{ wallet.balance }} €</h2>
        {% endif %}
        {% if not user.is_authenticated %}
            <h2>You must be logged-in to buy a book.</h2>
        {% endif %}
    </section>
    <section class="actions">
        <a href="{% url 'book:create' %}">CREATE YOUR BOOK</a>
        <a href="{% url 'book:ownedBooks' %}">OWNED BOOKS</a>
        <a href="{% url 'book:purchasedBooks' %}">PURCHASED BOOKS</a>
        <a href="{% url 'book:shop' %}">SHOP</a>
        <a href="{% url 'book:index' %}">MENU</a>
    </section>
{#    <section class="actions">#}
{#        {% if owned %}#}
{#            <a href="{% url 'book:create' %}">CREATE YOUR BOOK</a>#}
{#            <a href="{% url 'book:shop' %}">BUY A BOOK</a>#}
{#            <a href="{% url 'book:purchasedBooks' %}">SEE PURCHASED BOOKS</a>#}
{#        {% else %}#}
{#            <a href="{% url 'book:shop' %}">BUY A BOOK</a>#}
{#            <a href="{% url 'book:ownedBooks' %}">SEE YOUR BOOKS</a>#}
{#        {% endif %}#}
{#        <a href="{% url 'book:index' %}">MENU</a>#}
{#    </section>#}
    <section class="shop">
        {% if library %}
            {% for book in library %}
                <div class="book">
                    <div class="book-header">
                        <h2 class="title">{{ book.title }}</h2>
                        <div class="right">
                            <h2 class="gender">{{ book.gender }}</h2>
                            <p>{{ book.num_pages }} pages</p>
                        </div>
                    </div>
                    <div class="book-paragraph">
                        <p>{{ book.description }}</p>
                        <p>{{ book.publication_date }}</p>
                    </div>
                    {% if owned %}
                        <div class="book-footer">
                            <a href="{% url 'book:delete' book.id %}">DELETE</a>
                            <a href="{% url 'book:edit' book.id %}">EDIT</a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        {% else %}
            {% if owned %}
                <h1 class="error">You don't own any book.</h1>
            {% else %}
                <h1 class="error">You didn't purchased any book.</h1>
            {% endif %}
        {% endif %}
    </section>
</body>
</html>

book/templates/book/buy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if book %}
        <title>Buy {{ book.title }}</title>
    {% else %}
        <title>Book doesn't exists</title>
    {% endif %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'book/shop.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&display=swap" rel="stylesheet">
</head>
<body>
    <h1>DO YOU WANT TO BUY THIS BOOK?</h1>
    <section class="shop">
        <div class="book">
            <div class="book-header">
                <h2 class="title">{{ book.title }}</h2>
                <h2 class="gender">{{ book.gender }}</h2>
            </div>
            <div class="book-paragraph">
                <p>{{ book.description }}</p>
            </div>
            <div class="book-footer">
                <h3>{{ book.price }} €</h3>
                <form action="{% url 'book:buyBook' book.id %}" method="post">
                    {% csrf_token %}
                    <input name="yes" type="submit" value="YES">
                    <input name="no" type="submit" value="NO">
                </form>
            </div>
        </div>
    </section>

{#    <h1>You are about to buy {{ book.title }}, written by {{ book.author }}</h1>#}
{#    <h2>Price: {{ book.price }}</h2>#}
{#    <h3>Do you want to buy the book?</h3>#}

</body>
</html>

book/templates/book/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create your book</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'book/create.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    <div class="hero-block">
        <form action="{% url 'book:create' %}" method="post">
            {% csrf_token %}
            <h1>CREATE YOUR BOOK</h1>
            <div class="inputs">
                <div class="champs">
                    <label>Title:</label>
                    <label>Author:</label>
                    <label>Description:</label>
                    <label>Gender:</label>
                    <label>Number of pages:</label>
                    <label>Price</label>
                </div>
                <div class="champs2">
                    <input name="title" type="text">
                    <input name="author" type="text">
                    <input name="description" type="text">
                    <input name="gender" type="text">
                    <input name="num_pages" type="number">
                    <input name="price" step="0.01" type="number">
                </div>
            </div>
            <input name="create" class="submit-input" type="submit" value="Validate">
            <input name="cancel" class="submit-input" type="submit" value="Cancel">
        </form>
    </div>
</body>
</html>

book/templates/book/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm delete</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'book/delete.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@600&display=swap" rel="stylesheet">
</head>
<body>
    <section class="centered">
        <h1>ARE YOU SURE TO DELETE THE BOOK?</h1>
        <form action="{% url 'book:delete' book.id %}" method="post">
            {% csrf_token %}
            <input name="delete" type="submit" value="YES">
            <input name="cancel" type="submit" value="NO">
        </form>
    </section>

</body>
</html>

book/templates/book/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create your book</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'book/create.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    <div class="hero-block">
        <form action="{% url 'book:edit' book.id %}" method="post">
            {% csrf_token %}
            <h1>EDIT YOUR BOOK</h1>
            <div class="inputs">
                <div class="champs">
                    <label>Title:</label>
                    <label>Author:</label>
                    <label>Description:</label>
                    <label>Gender:</label>
                    <label>Number of pages:</label>
                    <label>Price</label>
                </div>
                <div class="champs2">
                    <input name="title" type="text" value="{{ book.title }}">
                    <input name="author" type="text" value="{{ book.author }}">
                    <input name="description" type="text" value="{{ book.description }}">
                    <input name="gender" type="text" value="{{ book.gender }}">
                    <input name="num_pages" type="number" value="{{ book.num_pages }}">
                    <input name="price" type="number" step="0.01" value="{{ book.price }}">
                </div>
            </div>
            <input name="edit" class="submit-input" type="submit" value="Validate">
            <input name="cancel" class="submit-input" type="submit" value="Cancel">
        </form>
    </div>
</body>
</html>

book/templates/book/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'book/index.css' %}">
{#    <link rel="stylesheet" href="{% static 'book/shop.css' %}">#}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="header">
        {% if user.is_authenticated %}
            <div>
                <img class="image" src="{% static 'book/icon.png' %}">
                <h1>Hello {{ user.username }}</h1>
            </div>
            <a href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
            <div>
                <img class="image" src="{% static 'book/icon.png' %}">
                <a href={% url 'accounts:login' %}>Login</a>
            </div>
            <a href="{% url 'accounts:signup' %}">Register</a>
        {% endif %}
    </div>
    <header class="hero-block text-center">
        <div class="hero-text-container">
            <h1 class="slide-in-top">WELCOME TO YOUR BOOK LIBRARY !</h1>
            <h2 class="slide-in-top">A library where you can store all your preferred books</h2>
            <a class="slide-in-bottom aButton" href="{% url 'book:create' %}">CREATE YOUR BOOK</a>
            <a class="slide-in-bottom aButton" href="{% url 'book:shop' %}">BUY A BOOK</a>
        </div>
    </header>

    <section class="menu">
        <div class="card">
            <h2>Your books</h2>
            <p>You can see here the books that you have created and sold on the shop</p>
            <div class="tags">
                <a href="{% url 'book:ownedBooks' %}">See your books</a>
            </div>
        </div>
        <div class="card">
            <h2>Purchased books</h2>
            <p>You can see here books that you have purchased on the shop. You can also see your creations as you want !</p>
            <div class="tags">
                <a href="{% url 'book:purchasedBooks' %}">See purchased books</a>
            </div>
        </div>
    </section>
</body>
</html>

book/templates/book/shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Shop</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'book/shop.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&display=swap" rel="stylesheet">
</head>
<body>
    <h1>BOOKS ON SALE</h1>
    <section class="wallet">
        {% if wallet %}
            <h2>YOUR WALLET: {{ wallet.balance }} €</h2>
        {% endif %}
        {% if not user.is_authenticated %}
            <h2>You must be logged-in to buy a book.</h2>
        {% endif %}
    </section>
    <section class="actions">
        <a href="{% url 'book:create' %}">CREATE YOUR BOOK</a>
        <a href="{% url 'book:ownedBooks' %}">OWNED BOOKS</a>
        <a href="{% url 'book:purchasedBooks' %}">PURCHASED BOOKS</a>
        <a href="{% url 'book:shop' %}">SHOP</a>
        <a href="{% url 'book:index' %}">MENU</a>
    </section>
    <section class="shop">
        {% if books %}
            {% for book, value in books.items %}
                <div class="book">
                    <div class="book-header">
                        <h2 class="title">{{ book.title }}</h2>
                        <h2 class="gender">{{ book.gender }}</h2>
                    </div>
                    <div class="book-paragraph">
                        <p>{{ book.description }}</p>
                    </div>
                    <div class="book-footer">
                        <h3>{{ book.price }} €</h3>
                        {% if value %}
                            <h3>Already bought</h3>
                        {% elif user.is_authenticated %}
                            <a href="{% url 'book:buyBook' book.id %}">BUY</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h1>There is no book for sale.</h1>
        {% endif %}
    </section>
</body>
</html>